### ISSUE TITLE
TMRL_SaveGhost.op plugin is unsigned -> requiring Club Access & Developer Signature mode

### ISSUE THREAD

**Issue by Chris92de** [trackmania-rl/tmrl#105]
This should be mentioned in the readme somewhere.

**Comment by yannbouteiller** [comment]
I submitted the new version for OpenPlanet to review, this should get signed soon.

**Comment by yannbouteiller** [comment]
This is fixed :)

To update to the new plugin:

- delete or rename the `TmrlData` folder
- execute `python -m tmrl --install`
