### ISSUE TITLE
How can I use WSL?????

### ISSUE THREAD

**Issue by CodKid1710** [trackmania-rl/tmrl#106]
Is there a way to be able to run the code via WSL

And run trackmania on windows?

**Comment by yannbouteiller** [comment]
If WSL supports Wine/Proton, which itself emulates Windows, but I don´t think so and this sounds rather absurd.

The TrackMania pipeline is fully supported on Windows and Linux (through Steam, i.e., Wine/Proton). Support for WSL sounds prohibitively tricky and is not planned, sorry.

**Comment by yannbouteiller** [comment]
PS: what you can probably do, however, is to run the Trainer/Server in WSL, and the Worker in Windows, this should work.

**Comment by CodKid1710** [comment]
thanks! :)
