### ISSUE TITLE
Disk full

### ISSUE THREAD

**Issue by LWY2012** [trackmania-rl/tmrl#112]
I have a problem because my C disk was full so I couldn't train more because is can't save new checkpoint.

**Can I move checkpoint files to another disk?**
If I can, how to change the code

**Comment by yannbouteiller** [comment]
Hi, you cloned the repo and performed a local installation (`pip install -e .`), you can change the code such that TMRL_FOLDER points to your other disk.

https://github.com/trackmania-rl/tmrl/blob/master/tmrl%2Fconfig%2Fconfig_constants.py#L19

**Comment by LWY2012** [comment]
oh! thanks very much!
