### ISSUE TITLE
got issue after running back my tmrl 

### ISSUE THREAD

**Issue by koi0823** [trackmania-rl/tmrl#117]
i have problem with my AI run after didnt run a few month ago now have this issue can i know what is happened 
@yannbouteiller 

Microsoft Windows [Version 10.0.22631.3447]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>python -m tmrl --record-reward
INFO:root:start recording
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tmrl\__main__.py", line 87, in <module>
    main(arguments)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tmrl\__main__.py", line 60, in main
    record_reward_dist(path_reward=cfg.REWARD_PATH)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tmrl\tools\record.py", line 39, in record_reward_dist
    data = client.retrieve_data(sleep_if_empty=0.01)  # we need many points to build a smooth curve
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tmrl\custom\utils\tools.py", line 72, in retrieve_data
    assert t_now - t_start < timeout, f"OpenPlanet stopped sending data since more than {timeout}s."
AssertionError: OpenPlanet stopped sending data since more than 10.0s.

C:\Users\user>

**Comment by koi0823** [comment]
![image](https://github.com/user-attachments/assets/7bb9f2ae-15b2-4bf0-b0f5-515b14af08da)

**Comment by yannbouteiller** [comment]
Hello, it looks like the OpenPlanet plugin stopped sending data.

**Comment by koi0823** [comment]
ya what should i do next ya ?
now i trying to reinstall what i see from other issue review

**Comment by koi0823** [comment]
issue solved after i reinstall but i want to ask i did zip my old tmrl folder can i replace the same file so i wont re-run again ?

**Comment by yannbouteiller** [comment]
Probably your openplanet plugin was just not up-to-date, reinstalling tmrl would have updated the plugin. You should be able to copy/paste your model, checkpoint and config.json in the relevant folders under the TmrlData directory.

**Comment by koi0823** [comment]
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

what is this error mean ya ?

when i run will suddenly stop it

**Comment by yannbouteiller** [comment]
It means that tmrl failed to communicate with the openplanet script.

**Comment by koi0823** [comment]
hi i got a question here about when i python -m tmrl --test

the wandb is not updated i am curious about how is work to the wandb see the test

![image](https://github.com/user-attachments/assets/bfc812fa-be59-4b09-bafd-e6cb05f2f53d)

**Comment by yannbouteiller** [comment]
"Testing" with SAC just means that you disable the random component of the policy and instead sample ftom the deterministic means. It is optional, wastes time and doesn't yield different performance than normal sampling in TrackMania, so I wouldn't be surprised if we disabled it.
