### ISSUE TITLE
Script compilation failed

### ISSUE THREAD

**Issue by heinzguenter** [trackmania-rl/tmrl#13]
[    ScriptEngine] [09:28:57] [Plugin_GrabData_0_1]  C:/Users/Malik/OpenplanetNext/Scripts/Plugin_GrabData_0_1.as (16, 1) : INFO : Compiling void Main()
[    ScriptEngine] [09:28:57] [Plugin_GrabData_0_1]  C:/Users/Malik/OpenplanetNext/Scripts/Plugin_GrabData_0_1.as (64, 21) :  ERR : No matching symbol 'CGameTerminal::ESGamePlaygroundUIConfig__EUISequence::Finish'
[    ScriptEngine] [09:28:57]  Script compilation failed!
Thats my openplanet log can somebody help me

**Comment by yannbouteiller** [comment]
Hi, apparently OpenPlanet cannot find the end of the track. Have you tried to reload the grab_data script after starting a track from the OpenPlanet menu?

This script is assuming you are on a track at the moment.

**Comment by yannbouteiller** [comment]
Okay the new working script is this one. I need to get it signed by Melissa (the OpenPlanet admin) but you can use it without a signature already if you have the club plan.
[Plugin_GrabData_0_1.zip](https://github.com/trackmania-rl/tmrl/files/8949963/Plugin_GrabData_0_1.zip)

**Comment by yannbouteiller** [comment]
I have updated the resources.zip file, this should correct the issue.

To update, perform a clean install (delete the TmrlData folder and the content of OpenPlanetNext/Scripts, pip uninstall tmrl, and pip install tmrl again).

Feel free to respond/reopen in case you need more help doing that :)
