### ISSUE TITLE
Script compiling fails in Openplanet and program does not run.

### ISSUE THREAD

**Issue by SwiftGodDev** [trackmania-rl/tmrl#2]
I tried to run tmrl using the given instructions but it fails to run. This is the error given in the command prompt:

Traceback (most recent call last):
  File "tmrl/run.py", line 6, in <module>
    import tmrl.config.config_constants as cfg
  File "g:\ubisoft\ubisoft game launcher\games\trackmania\tmrl\tmrl\__init__.py", line 19, in <module>
    import tmrl.sac
  File "g:\ubisoft\ubisoft game launcher\games\trackmania\tmrl\tmrl\sac.py", line 13, in <module>
    import tmrl.sac_models
  File "g:\ubisoft\ubisoft game launcher\games\trackmania\tmrl\tmrl\sac_models.py", line 16, in <module>
    from tmrl.nn import SacLinear, TanhNormalLayer
  File "g:\ubisoft\ubisoft game launcher\games\trackmania\tmrl\tmrl\nn.py", line 14, in <module>
    from tmrl import partial
ImportError: cannot import name 'partial' from partially initialized module 'tmrl' (most likely due to a circular import) (g:\ubisoft\ubisoft game launcher\games\trackmania\tmrl\tmrl\__init__.py)

This is my Openplanet log: 
[Openplanet.log](https://github.com/trackmania-rl/tmrl/files/6772110/Openplanet.log)

**Comment by yannbouteiller** [comment]
Oh wow, I didn't know we had open-sourced this project yet, it is still under development and not open-source ready yet. I am sorry for the inconvenience, I will see if I can make the repo private again until it is ready for publication.

**Comment by yannbouteiller** [comment]
Hello, we have made the repo open-source ready, now everything should work. The OpenPlanet script was outdated, a new script is now in the repo, and we have updated the installation instruction, please check it out :)

And apologies for the time you have input into making the repo work while it was not ready yet, from now on we will maintain a stable version on the master branch. Please reopen the issue if you experience other difficulties.

**Comment by SwiftGodDev** [comment]
I was wondering if you could provide some instructions for using tmrl with "Trackmania Nations Forever" because openplanet cannot be used with TMNF.
