### ISSUE TITLE
Still working on this project?

### ISSUE THREAD

**Issue by glederrey** [trackmania-rl/tmrl#28]
Hey, 

I was wondering if you're still working on this project? I'd love to contribute to it if it's possible in any way. =)

(I'm a Data Scientist who worked on GANs during my PhD and I'd love to learn about reinforcement learning!)

**Comment by yannbouteiller** [comment]
Hello!

Sorry for the late answer. For sure we are still working on the project, version 0.4.0 is being developped on the `yb/dev` branch and should be released

**Comment by yannbouteiller** [comment]
If you want to learn deep RL and are a GAN expert maybe you might like to implement better CV-based approaches than the current vanilla SAC/REDQ? Just an idea =)

**Comment by yannbouteiller** [comment]
Note that a cool thing about our little application here is that we are dealing with the real world: you will not only have to learn deep RL the MuJoCo way, but also to apply it to a real application with time constraints.

Hugely computational models won't work at inference time.

**Comment by glederrey** [comment]
Hey Yann, 

Thanks a lot for the answer. =) Do you have a discord where you dev? (I guess you're not the only one working on it ^^) If it's the case, I'd love to join it to discuss it in more details. =)

You can add me Tokay#7909 =)

**Comment by yannbouteiller** [comment]
We don't have a dedicated discord yet but people have asked before and that sounds like a good idea, maybe we should create one =)
