### ISSUE TITLE
Change MAP for incremental learning

### ISSUE THREAD

**Issue by Thomas-Raynaud-ENSTA** [trackmania-rl/tmrl#31]
Hi!

In the scope of a school project, alongside with my team we woud like to use your library to create an AI that drives in TrackMania. We were wondering if it was possible to change the map on which the AI is driving. In fact, we managed to get it run on different map, although it keeps reseting after a couple of second.

Therefore, is there a way to setup new maps for training/testing? If yes, where should we look at?

Thanks!

**Comment by yannbouteiller** [comment]
Hi Thomas, sure there is a way of doing so ;)

Just follow the instructions in the `Getting started` guide [here](https://github.com/trackmania-rl/tmrl/blob/master/readme/get_started.md#train-your-own-self-driving-ai).

(Closing as this is not an issue, please use [discussions](https://github.com/trackmania-rl/tmrl/discussions) for this type of questions)

**Comment by yannbouteiller** [comment]
(The reason why it restarts on other maps is because you have not built a reward function for these maps, thus the rtgym environment believes your car is running loose away from the track)

**Comment by Thomas-Raynaud-ENSTA** [comment]
Thank you for your reply and your instructions. This is much clearer!
