### ISSUE TITLE
Round number/ correct round time

### ISSUE THREAD

**Issue by NumseBacon** [trackmania-rl/tmrl#4]
Hello!

So on the wandb.ai website it says my round_time is around 200, but in reality the round times are around 20-23 while it trains etc. Also would it be possible to see how many times the ai has resat on a map/how many times it has driven it?s

**Comment by edigeze** [comment]
Hello NumseBacon,
So if you want to see how many resets the ai did, it's corresponding to the horizontal axis (step).
If you want to see how far the car went, you can check that at return_train (10 000 = 1Km).
20-23 is corresponding to the amount of epoch, not the round_time.
The round_time is the time spent on each round.
Good luck with your training  ;)

**Comment by NumseBacon** [comment]
No no I meant 20-23 as in the AI drives from start to finish of map in 20-23 seconds. Also you say round_time is time spent on each round, but for me it increases?

**Comment by NumseBacon** [comment]
Also I wanna ask about this: Ive been training for about 10-12 hours and it keeps wiggling a lot on the track, and hitting walls you can see it in this video: [https://youtu.be/2z5FD-38Pwk](https://youtu.be/2z5FD-38Pwk)    It has only gained a little time on the track. The 17,945 time you see on the ranking tab is by me where I didnt drive it as fast as I could. I would imagine it could be faster if it could stop hitting the walls? Should I reset the data completely or just keep training?

I also noticed when I opened OBS to record the video I got more of the "Time-step timed out" errors but It drove faster than when training?

**Comment by yannbouteiller** [comment]
Hi!

The "round time" is not the duration that the AI took to complete the track, that would rather be the "episode length" (in number of time-steps, which we default to 0.05s each). Instead, we arbitrarily call a "round" a fixed number of training iterations between which training results are printed/sent to wandb.

To give you an idea, with the RTX 3080 that we use for training, a round is indeed about 20-30s, if your round time is 200s the default hyperparameters are likely not fit for your GPU, and training will likely be ~10 times longer.

I also see in your video that your track has a small slope at the beginning. This might disrupt SAC with the default history of 4 LIDAR measurements equally spaced in time that I suppose you use as your observation space, because of the possible non-markovness of this part of the environment. Keep in mind that RL expects to see a similar behavior of the environment for similar observation-action pairs :)

**Comment by NumseBacon** [comment]
When I first installed it I dragged the pretrained network into the weights folder, and began training my network. And Ive been letting it run like that, idk if it then uses something from the pretrained network? 

When you say "episode length" for time to finish the track, do you mean episode_length_test or episode_length_train, I would imagine train cuz thats probably the one from when its trains the network right?

How would I reset my data/start from scratch?

**Comment by yannbouteiller** [comment]
The GIF is a placeholder at the moment, it is @edigeze driving. We should replace this with an actual footage of the provided AI now that we have open-sourced the repo.

episode_length_test and episode_length_train are more or less the same things: train is while the AI trains, and test is because once in a while the AI runs a "test" episode where it takes deterministic actions instead of stochastic actions, in some environments this is known to yield a marginal improvement but in TMRL I don't thing there is any noticeable such improvement, it is rather for debugging purpose.

To restart from scratch, you have two possibilities. Currently, the "clean" way is to go to tmrl/tmrl/config/config_constants.py and change the value of the RUN_NAME constant.
The other solution is to go to tmrl/tmrl/data/checkpoint and delete the .pkl object (this is a saved state of your training), then go to tmrl/tmrl/data/weights/ and remove all .pkl objects (these are snapshots of your trained networks).

**Comment by NumseBacon** [comment]
Alright nice! Kinda sucks you have to have your computer on all the time haha

**Comment by yannbouteiller** [comment]
Difficult to run the game with the computer turned off, but you can stop training and restart later, it will work.

**Comment by NumseBacon** [comment]
@yannbouteiller Hello... Im now getting the error: ModuleNotFoundError: No module named 'tmrl'

**Comment by yannbouteiller** [comment]
Hi, this is pretty weird. This is the vgamepad library that fails to connect to vigembus for some reason. Something has changed in your configuration I guess because it use to work and now it doesn't? Do you have more info?

**Comment by NumseBacon** [comment]
No im trying it on a more powerful computer. I everything exactly as I did on my own computer, but it just keeps giving that error, even though ive tried uninstalling and installing multiple times

**Comment by yannbouteiller** [comment]
The "Time-step timed out" mean that your PC is not powerful enough to run the AI an trackmania in parallel. What you can try is to reduce the graphics in trackmania to the minimum, and in particular set a maximum frame rate of 30 fps. To test whether the algo works, you should use the provided map and the provided neural network, the car should be driving quite well.

You should see roughly the same as what you see at the beginning of this video : https://www.youtube.com/watch?v=LN29DDlHp1U 

(@edigeze , I just made the video public)

**Comment by NumseBacon** [comment]
The game is running at 150 fps :/

**Comment by yannbouteiller** [comment]
This is why you should reduce it to 30 fps, there is an option for that in the graphics setting of TM2020. Running the actor network consumes quite a bit of CPU, and if trackmania eats too much of it there is not enough left for inference. "Time-step timed out" means that your PC is taking too much time to take a screenshot, compute the lidar observation, and feed it to the neural network. If this happens only once in a while you won't notice, but if it happens repeatedly this will break the AI.

**Comment by NumseBacon** [comment]
I capped maximum fps at 30 fps and it still doesnt drive

**Comment by NumseBacon** [comment]
I feel like its because im using an earlier version of vigembus

**Comment by yannbouteiller** [comment]
If so, just uninstall vigembus and vgamepad, and then reinstall vgamepad, it will automatically install the right version og vigembus.

**Comment by yannbouteiller** [comment]
I think the new version of trackmania is very CPU-hungry. I have tested tmrl yesterday and I had to cap trackmania to 30fps and put graphics to low to make it work, while I use to run this at max quality with no issue. I'm very busy these days but I'll do some further testing when I have a moment.

**Comment by NumseBacon** [comment]
Well if I get the newer version of vigembus it gives me the error so it doesnt work either

**Comment by yannbouteiller** [comment]
You should not install vigembus from the official website, the right version is packaged in vgamepad and is installed automatically when installing vgamepad.

**Comment by NumseBacon** [comment]
Yea ik that one doesnt work for me

**Comment by yannbouteiller** [comment]
Really? That is unheard of, what version of vigembus were you using in this video you showed earlier? vgamepad seemed to work correctly at this point. If you have more info regarding why it doesn't work please share.

**Comment by NumseBacon** [comment]
116.116 from their github is the only that's kinda working but doesn't drive. Earlier was just vgamepad from modules

**Comment by NumseBacon** [comment]
https://youtu.be/AmWAJ6g2HAo

**Comment by yannbouteiller** [comment]
Oh wow, something is very wrong! You don't show the CPU stats but if the GPU is a 3090 I expect your overall PC config to be much faster that what I use here, you should definitely not get those timestep timeouts even when running TM2020 at full speed.

So, I see two issues here.

First, vgamepad doesn't work correctly on your PC for some reason (I think even when it seems to work actually it does nothing). Can you try the following in this order:

1) pip install -U pip
2) pip uninstall vgamepad
3) Manually uninstall all versions of vigembud (Nefarius Virtual Gamepad Emulation Driver)
4) pip install vgamepad --no-cache-dir
5) you should get this pop-up: https://paste.pics/0a1687ffdc31cee1420f68f4b5cbd4f6
6) accept the terms, install, allow the msi file to do the install, finish installation
7) go to gamepad tester: https://gamepad-tester.com
8) execute the following python script and check that the right buttons and joystick values are set accordingly in gamepad tester:

```python
import vgamepad as vg
import time

gamepad = vg.VX360Gamepad()

# press a button to wake the device up
gamepad.press_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_A)
gamepad.update()
time.sleep(0.5)
gamepad.release_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_A)
gamepad.update()
time.sleep(0.5)

# press buttons and things
gamepad.press_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_A)
gamepad.press_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER)
gamepad.press_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN)
gamepad.press_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT)
gamepad.left_trigger_float(value_float=0.5)
gamepad.right_trigger_float(value_float=0.5)
gamepad.left_joystick_float(x_value_float=0.0, y_value_float=0.2)
gamepad.right_joystick_float(x_value_float=-1.0, y_value_float=1.0)

gamepad.update()

time.sleep(1.0)

# release buttons and things
gamepad.release_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_A)
gamepad.release_button(button=vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT)
gamepad.right_trigger_float(value_float=0.0)
gamepad.right_joystick_float(x_value_float=0.0, y_value_float=0.0)

gamepad.update()

time.sleep(1.0)

# reset gamepad to default state
gamepad.reset()

gamepad.update()

time.sleep(1.0)
```

Second, there appears to be something on you PC that keeps tmrl from running fast: if your CPU is reasonable for a RTX3090 PC you should not get any of these timestep timeouts.

Can you

1) check whether your CPU (not GPU) is indeed saturated (and why)
2) keep the TM2020 window open and run the benchmarking script: `python tools\benchmark_environment.py` , this should take 1-2 minutes before printing the results (you can move around with your keyboard arrows in the meantime to check whether your reward is working)

**Comment by yannbouteiller** [comment]
Hi @NumseBacon, there was no option to compile for Windows Driver specifically in Visual Studio (only x64 and x86 architectures), but I still have updated the vigem-client DLL files in the [vgamepad repo](https://github.com/yannbouteiller/vgamepad).

I don't expect this to change much but who knows... If you care to try, you can clone the vgamepad repo and inspall it with `pip install .` or `pip install -e .`, if that miraculously works on Windows Server I will update the the PyPI package.

**Comment by NumseBacon** [comment]
Sadly it didnt

**Comment by yannbouteiller** [comment]
This seems related to https://github.com/ViGEm/ViGEmBus/issues/85

**Comment by NumseBacon** [comment]
Oh nice. I will test sometime

**Comment by yannbouteiller** [comment]
If you try please tell me if it works, so I add this in the vgamepad repo

**Comment by yannbouteiller** [comment]
@NumseBacon the repo has been on standby for a while because I had other projects, but I have just found a bug that has probably hurted your training performance badly (sample time in particular). It was lurking here since May... I will soon push the fix to master.

**Comment by yannbouteiller** [comment]
Yep, we do this all the time and it it made easy in the new version (in fact I think the new version works only in this case, I have to fix that, will probably do today). If you are on a local network, you can change the config.json file located in your home folder (TmrlData/config) for this. You just set the public ip of the server to the local IP of the computer where the server is, and set localhost server and/or localhost worker to false (you can safely set them both to false)

**Comment by NumseBacon** [comment]
Lets call my current computer pc1 and the one i want to use tmrl on pc2. Is the server config on pc1 or 2? and then is it possible to close pc1 and just keep the pc2 running?

**Comment by yannbouteiller** [comment]
For seeing the data, we use wandb. You can see the data online on the public wandb project that we provide, or you can use your own wandb account by modifying the wandb credentials in config.json

**Comment by NumseBacon** [comment]
and the rest?

**Comment by yannbouteiller** [comment]
The config.json file has to be adapted on all the computers you use. The point of tgis feature is not to visualize the data on another computer (since they are online on wandb you can do this in any case), but to have trackmania running on one to several computers to collect samples, and have the trainer running on another computer with a beefy GPU.

**Comment by NumseBacon** [comment]
So ie I could have multiple computers running server and collecting samples and then one computer running trainer and learning faster due to more samples?

**Comment by yannbouteiller** [comment]
Yes, exactly. That being said you would probably want to change hyperparameters of SAC if you were doing this, and at the moment it is not possible yet without changing the code (the hyperparameters are in config_objects.py at the moment, I'll move them to a json file soon)

**Comment by NumseBacon** [comment]
Whats with the hyperparameters?

**Comment by yannbouteiller** [comment]
Well, let's say you have 2 PC running trackmania instead of 1, then you may want to use a batch size larger than the 256 which is currently the default, for instance.

**Comment by yannbouteiller** [comment]
In fact, personally I use this feature so that I can have my old laptop running trackmania, and the training happening on a dedicated GPU server

**Comment by NumseBacon** [comment]
Wait so. the computer with the training isnt even running trackmania? only the cmd "python -m tmrl --trainer"? and the pc running trackmania is running --worker and --server?

**Comment by yannbouteiller** [comment]
Yes in my case that's exactly what is happening. So I can run training on a Linux-based HPC.

**Comment by NumseBacon** [comment]
May I ask what dedicated gpu server you use?

**Comment by yannbouteiller** [comment]
I use to use ComputeCanada (SLURM-based server for canadian research), but nowadays I am instead using an Ubuntu machine that has a RTX3080 for my lab.

**Comment by NumseBacon** [comment]
So theres no website so I also can rent one?

**Comment by yannbouteiller** [comment]
There is AWS and Microsoft Azure for instance, but if you have a good GPU there is no real point in doing this (it is quite expensive to rent). As far as I can tell, the bottleneck for training is more the fact that 1 single PC running trackmania in real-time produces very few samples, I believe.

**Comment by yannbouteiller** [comment]
(If we had 100 PCs running TrackMania in parallel, I believe training could be much more efficient. There is also the fact that the current observations we feed to the neural network are quite far from Markov, because for instance they don't enable the NN to know that the car has crashed in a wall 10 time-steps ago, which seems to have a certain influence on the dynamics of the car)

**Comment by NumseBacon** [comment]
well 100 is a lot of PCs and that would be a lot of data

**Comment by yannbouteiller** [comment]
Yes but we throw the data away periodically, so the more we get, the better. In a paper where ETH people and Sony apply SAC in Gran Turismo, they are basically using 60 or 80 cars in parallel, at at speed that is probably faster than real time (https://arxiv.org/abs/2008.07971)

**Comment by NumseBacon** [comment]
well that AI has probably also been learning for hundreds of hours

**Comment by yannbouteiller** [comment]
(closing as this is more a discussion than an issue now, but feel free to continue using the thread for discussion)

**Comment by NumseBacon** [comment]
@yannbouteiller 
Would it possible to use TMInterface to speed up the training for the RL?
Like in this video? https://youtu.be/SX08NT55YhA?t=474

**Comment by yannbouteiller** [comment]
> @yannbouteiller Would it possible to use TMInterface to speed up the training for the RL? Like in this video? https://youtu.be/SX08NT55YhA?t=474

If your PC is a beast it would be possible to get some marginal acceleration of sample collection using this, but this would likely be small because the bottleneck in the default tmrl environment is screenshot capture and LIDAR computation. Plus, apart if TMInterface enables us to pause the game so that we can be hacky with time, this would come with an increased variance time-wise.

The real/scalable way to go if you need to accelerate sample collection is to use several workers, on different computers running the game in parallel.
