### ISSUE TITLE
Feature Request: migrate from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [trackmania-rl/tmrl#40]
Hi, very cool repo. Would it be possible for it to be upgraded from gym to gymnasium? [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the maintained version of openai gym and is compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib) and [tianshou](https://github.com/thu-ml/tianshou) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon).  

This repository is currently listed in the gymnasium [third party environments](https://gymnasium.farama.org/environments/third_party_environments/) but we are cleaning the list up to only include maintained gymnasium-compatible repositories.  

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues.

**Comment by yannbouteiller** [comment]
Hi, we will migrate to gymnasium shortly alongside `rtgym`, some people have already requested we do :)

**Comment by yannbouteiller** [comment]
`tmrl` and `rtgym` now support `gymnasium` instead of `gym` since [version 0.5.0](https://github.com/trackmania-rl/tmrl/releases/tag/v0.5.0)

Note that `tmrl` had already migrated to the `truncated` / `terminated` signature when `gym` did. Our SAC implementation has always used the difference between these two signals and used the `info` dictionary for that purpose when the change was not yet introduced in the newer versions of `gym`.

**Comment by elliottower** [comment]
> `tmrl` and `rtgym` now support `gymnasium` instead of `gym` since [version 0.5.0](https://github.com/trackmania-rl/tmrl/releases/tag/v0.5.0)
> 
> Note that `tmrl` had already migrated to the `truncated` / `terminated` signature when `gym` did. Our SAC implementation has always used the difference between these two signals and used the `info` dictionary for that purpose when the change was not yet introduced in the newer versions of `gym`.

Thanks! My bad, I didn’t see the truncated and terminated changes were already switched. Excited to play around with training agents:)
