### ISSUE TITLE
OpenPlanet plugin has invalid signature

### ISSUE THREAD

**Issue by mah51** [trackmania-rl/tmrl#5]
I followed the readme and get the following error in open planet logs on reload.

![image](https://user-images.githubusercontent.com/47287285/133555078-f9b1a28e-bae2-44e3-a3a3-ad3ad1a4e94b.png)

**Comment by yannbouteiller** [comment]
Hello mah51, so you need to paste the script `Plugin_GrabData_0_1.as.sig` in the folder `C:\Users\username\OpenplanetNext\Scripts\` .  It is the signature of the first script.

**Comment by AndrejGobeX** [comment]
I have the same issue, I have pasted both files in the `C:\Users\username\OpenplanetNext\Scripts\`

**Comment by AndrejGobeX** [comment]
Fixed it, git clone and then copy both files to `C:\Users\username\OpenplanetNext\Scripts\`

**Comment by yannbouteiller** [comment]
Sorry, I am not sure what the issue was and how you fixed it exactly?

**Comment by yannbouteiller** [comment]
You mean pypi? @edigeze can you delete this useless pypi repo please ?

**Comment by AndrejGobeX** [comment]
No, haven't tried pypy

**Comment by yannbouteiller** [comment]
Corrected in the last release.
