### ISSUE TITLE
config/config.json not generating

### ISSUE THREAD

**Issue by CodKid1710** [trackmania-rl/tmrl#87]
I am trying to use TMRL with a keras PPO ai and I was having some problems with the input so I tried a clean install I uninstalled tmrl, then deleted the tmrlData folder, and then reinstalled tmrl, but it didn't generate the tmrlData

Can somebody help, I am on windows 11, using vscode

**Comment by yannbouteiller** [comment]
Hi, this is strange, pip is supposed to recreate the TmrlData folder fresh when you reinstall tmrl after deleting this folder 🤔

**Comment by CodKid1710** [comment]
I fix the issue, instead of install version 0.6.1, I installed version 0.5.3 and then it generated the tmrlData

**Comment by yannbouteiller** [comment]
Very weird, I don't understand how this is possible, we need to fix this if other people get the same issue.

The TmrlData folder downloaded with versions < 0.6 is not compatible with version 0.6 1

**Comment by CodKid1710** [comment]
sorry what I meant is uninstall version 0.6.0 and install version 0.5.3, after that do NOT update to version 0.6.1

**Comment by yannbouteiller** [comment]
Well I tried uninstalling tmrl 0.6.1, deleted the `TmrlData` folder and reinstalled 0.6.1 via
```
pip install tmrl --no-cache
```
and it recreated the `TmrlData` folder properly, I really don't see how this can fail on your PC, especially if you don't encounter the issue with 0.5.3, perhaps your firewall blocks the download of 0.6.1's resources folder for reasons that I don't understand (both 0.5.3 and 0.6.1 are hosted on github)
